
        const translations = {
            en: {
                home: "Home",
                feature: "feature",
                maintenance: "Maintenance",
                feedback: "Feedback",
                build_websites: "We build powerful websites",
                unlock_power: "Unlock the most powerful websites for business with 100,000+ people globally",
                easy_build: "Easy build powerful websites",
                modern_websites: "Our team is creating modern websites for your webshop, business in days",
                unlock_access: "Unlock Access",
                easy_build_most: "Easy build most powerful websites",
                modern_websites_2: "Our team is creating modern websites for your webshop, business in days",
                unlock_access_2: "Unlock Access",
                easy_build_strategies: "Easy build powerful strategies",
                modern_websites_3: "Our team is creating modern websites for your webshop, business in days",
                unlock_access_3: "Unlock Access",
                basic: "Basic",
                basic_price: "$9.99/month",
                per_site: "per month",
                simple_design: "Simple Design and Layout",
                home_page: "Home Page",
                contact_form: "Contact Form",
                responsive_design: "Responsive Design",
                basic_seo: "Basic SEO Setup",
                get_started: "Get started",
                pro: "Pro",
                pro_price: "$17.99/month",
                all_basic: "All from Basic version",
                advanced_design: "Advanced Design",
                content_management: "Content Management System",
                social_media: "Social Media Integration",
                enhanced_seo: "Enhanced SEO Keysearch",
                premium: "Premium",
                premium_price: "$25.99/month",
                all_pro: "All from Pro",
                ecommerce: "E_commerce Functionality",
                advanced_analytics: "Advanced Analytics",
                blog_setup: "Blog Setup and Integration",
                custom_graphics: "Custom Graphics and Branding",
                website_maintenance: "Website Maintenance",
                get_site_plan: "Get site plan",
                ultra: "Ultra",
                ultra_price: "$32.99/month",
                all_premium: "All from Premium",
                additional_pages: "Additional Pages",
                content_creation: "Content Creation",
                email_newsletter: "Email Newsletter Setup",
                multilingual_support: "Multilingual Support",
                ongoing_maintenance: "Ongoing Maintenance",
                custom_development: "Custom Development"
            },
            nl: {
                home: "Home",
                feature: "feature",
                maintenance: "Onderhoud",
                feedback: "Feedback",
                build_websites: "We bouwen krachtige websites",
                unlock_power: "Ontgrendel de krachtigste websites voor bedrijven met 100.000+ mensen wereldwijd",
                easy_build: "Gemakkelijk krachtige websites bouwen",
                modern_websites: "Ons team maakt moderne websites voor uw webshop, bedrijf in dagen",
                unlock_access: "Ontgrendellen",
                easy_build_most: "Gemakkelijk de krachtigste websites bouwen",
                modern_websites_2: "Ons team maakt moderne websites voor uw webshop, bedrijf in dagen",
                unlock_access_2: "Ontgrendellen",
                easy_build_strategies: "Gemakkelijk krachtige strategieën bouwen",
                modern_websites_3: "Ons team maakt moderne websites voor uw webshop, bedrijf in dagen",
                unlock_access_3: "Ontgrendellen",
                basic: "Basis",
                basic_price: "€9.99/maand",
                per_site: "per maand",
                simple_design: "Eenvoudig ontwerp en layout",
                home_page: "Startpagina",
                contact_form: "Contactformulier",
                responsive_design: "Responsief ontwerp",
                basic_seo: "Basis SEO_instelling",
                get_started: "begin",
                pro: "Pro",
                pro_price: "€17.99/maand",
                all_basic: "Alles van Basisversie",
                advanced_design: "Geavanceerd ontwerp",
                content_management: "Content Management Systeem",
                social_media: "Social media_integratie",
                enhanced_seo: "Verbeterde SEO_sleutelzoektocht",
                premium: "Premium",
                premium_price: "€25.99/maand",
                all_pro: "Alles van Pro",
                ecommerce: "E_commerce functionaliteit",
                advanced_analytics: "Geavanceerde analyse",
                blog_setup: "Blogopzet en integratie",
                custom_graphics: "Aangepaste grafische afbeeldingen en branding",
                website_maintenance: "Website onderhoud",
                get_site_plan: "begin",
                ultra: "Ultra",
                ultra_price: "€32.99/maand",
                all_premium: "Alles van Premium",
                additional_pages: "Extra pagina's",
                content_creation: "Contentcreatie",
                email_newsletter: "E_mailnieuwsbrief opzetten",
                multilingual_support: "Meertalige ondersteuning",
                ongoing_maintenance: "Voortdurend onderhoud",
                custom_development: "Aangepaste ontwikkeling"
            },
            fr: {
                home: "Home",
                feature: "feature",
                maintenance: "Entretien",
                feedback: "Retour d'information",
                build_websites: "Nous construisons des sites web puissants",
                unlock_power: "Déverrouillez les sites web les plus puissants pour les entreprises avec plus de 100 000 personnes dans le monde entier",
                easy_build: "Facile à construire des sites web puissants",
                modern_websites: "Notre équipe crée des sites web modernes pour votre boutique en ligne, entreprise en quelques jours",
                unlock_access: "Déverrouiller l'accès",
                easy_build_most: "Facile à construire les sites web les plus puissants",
                modern_websites_2: "Notre équipe crée des sites web modernes pour votre boutique en ligne, entreprise en quelques jours",
                unlock_access_2: "Déverrouiller l'accès",
                easy_build_strategies: "Facile à construire des stratégies puissantes",
                modern_websites_3: "Notre équipe crée des sites web modernes pour votre boutique en ligne, entreprise en quelques jours",
                unlock_access_3: "Déverrouiller l'accès",
                basic: "De base",
                basic_price: "$9.99/mois",
                per_site: "Par site par mois",
                simple_design: "Conception et mise en page simples",
                home_page: "Page d'accueil",
                contact_form: "Formulaire de contact",
                responsive_design: "Conception réactive",
                basic_seo: "Configuration SEO de base",
                get_started: "Commencer",
                pro: "Pro",
                pro_price: "$17.99/mois",
                all_basic: "Tout de la version de base",
                advanced_design: "Conception avancée",
                content_management: "Système de gestion de contenu",
                social_media: "Intégration des médias sociaux",
                enhanced_seo: "Recherche de mots_clés SEO améliorée",
                premium: "Premium",
                premium_price: "$25.99/mois",
                all_pro: "Tout de Pro",
                ecommerce: "Fonctionnalité de commerce électronique",
                advanced_analytics: "Analytique avancée",
                blog_setup: "Configuration et intégration de blog",
                custom_graphics: "Graphiques et branding personnalisés",
                website_maintenance: "Maintenance du site web",
                get_site_plan: "Obtenir un plan de site",
                ultra: "Ultra",
                ultra_price: "$32.99/mois",
                all_premium: "Tout de Premium",
                additional_pages: "Pages supplémentaires",
                content_creation: "Création de contenu",
                email_newsletter: "Configuration de la newsletter par e_mail",
                multilingual_support: "Support multilingue",
                ongoing_maintenance: "Maintenance continue",
                custom_development: "Développement personnalisé"
            },
            tr: {
                home: "Ev",
                feature: "özellik",
                maintenance: "Bakım",
                feedback: "Geri bildirim",
                build_websites: "Güçlü web siteleri oluşturuyoruz",
                unlock_power: "Dünyada 100.000'den fazla kişiyle işletmeler için en güçlü web sitelerini açın",
                easy_build: "Kolayca güçlü web siteleri oluşturun",
                modern_websites: "Ekibimiz, çevrimiçi mağazanız için modern web sitelerini birkaç gün içinde oluşturuyor",
                unlock_access: "Erişimi aç",
                easy_build_most: "En güçlü web sitelerini kolayca oluşturun",
                modern_websites_2: "Ekibimiz, çevrimiçi mağazanız için modern web sitelerini birkaç gün içinde oluşturuyor",
                unlock_access_2: "Erişimi aç",
                easy_build_strategies: "Kolayca güçlü stratejiler oluşturun",
                modern_websites_3: "Ekibimiz, çevrimiçi mağazanız için modern web sitelerini birkaç gün içinde oluşturuyor",
                unlock_access_3: "Erişimi aç",
                basic: "Temel",
                basic_price: "$9.99/ay",
                per_site: "Site başına aylık",
                simple_design: "Basit Tasarım ve Düzen",
                home_page: "Ana Sayfa",
                contact_form: "İletişim Formu",
                responsive_design: "Duyarlı Tasarım",
                basic_seo: "Temel SEO Ayarı",
                get_started: "Başlamak",
                pro: "Pro",
                pro_price: "$17.99/ay",
                all_basic: "Temel sürümden her şey",
                advanced_design: "Gelişmiş Tasarım",
                content_management: "İçerik Yönetim Sistemi",
                social_media: "Sosyal Medya Entegrasyonu",
                enhanced_seo: "Geliştirilmiş SEO Anahtar Kelime Araştırması",
                premium: "Premium",
                premium_price: "$25.99/ay",
                all_pro: "Pro'dan her şey",
                ecommerce: "E-ticaret İşlevselliği",
                advanced_analytics: "Gelişmiş Analitik",
                blog_setup: "Blog Kurulumu ve Entegrasyonu",
                custom_graphics: "Özel Grafikler ve Markalama",
                website_maintenance: "Web Sitesi Bakımı",
                get_site_plan: "Site Planı Al",
                ultra: "Ultra",
                ultra_price: "$32.99/ay",
                all_premium: "Premium'dan her şey",
                additional_pages: "Ek Sayfalar",
                content_creation: "İçerik Oluşturma",
                email_newsletter: "E-posta Bülteni Kurulumu",
                multilingual_support: "Çok Dilli Destek",
                ongoing_maintenance: "Sürekli Bakım",
                custom_development: "Özel Geliştirme"

            },

            arab: {
                home: "الرئيسية",
                feature: "ميزة",
                maintenance: "الصيانة",
                feedback: "التعليقات",
                build_websites: "نبني مواقع ويب قوية",
                unlock_power: "افتح أقوى مواقع الويب للأعمال التجارية مع أكثر من 100,000 شخص حول العالم",
                easy_build: "بناء مواقع ويب قوية بسهولة",
                modern_websites: "فريقنا يصمم مواقع ويب حديثة لمتجرك الإلكتروني، عملك في غضون أيام",
                unlock_access: "افتح الوصول",
                easy_build_most: "بناء أقوى مواقع الويب بسهولة",
                modern_websites_2: "فريقنا يصمم مواقع ويب حديثة لمتجرك الإلكتروني، عملك في غضون أيام",
                unlock_access_2: "افتح الوصول",
                easy_build_strategies: "بناء استراتيجيات قوية بسهولة",
                modern_websites_3: "فريقنا يصمم مواقع ويب حديثة لمتجرك الإلكتروني، عملك في غضون أيام",
                unlock_access_3: "افتح الوصول",
                basic: "أساسي",
                basic_price: "$9.99/شهر",
                per_site: "لكل موقع شهرياً",
                simple_design: "تصميم وتخطيط بسيط",
                home_page: "الصفحة الرئيسية",
                contact_form: "نموذج الاتصال",
                responsive_design: "تصميم متجاوب",
                basic_seo: "إعدادات SEO الأساسية",
                get_started: "ابدأ الآن",
                pro: "احترافي",
                pro_price: "$17.99/شهر",
                all_basic: "كل شيء من الإصدار الأساسي",
                advanced_design: "تصميم متقدم",
                content_management: "نظام إدارة المحتوى",
                social_media: "دمج وسائل التواصل الاجتماعي",
                enhanced_seo: "البحث المحسن عن الكلمات الرئيسية لـ SEO",
                premium: "مميز",
                premium_price: "$25.99/شهر",
                all_pro: "كل شيء من الإصدار الاحترافي",
                ecommerce: "وظائف التجارة الإلكترونية",
                advanced_analytics: "تحليلات متقدمة",
                blog_setup: "إعداد وتكامل المدونة",
                custom_graphics: "رسومات مخصصة وعلامات تجارية",
                website_maintenance: "صيانة الموقع",
                get_site_plan: "احصل على خطة الموقع",
                ultra: "ألترا",
                ultra_price: "$32.99/شهر",
                all_premium: "كل شيء من الإصدار المميز",
                additional_pages: "صفحات إضافية",
                content_creation: "إنشاء المحتوى",
                email_newsletter: "إعداد النشرة الإخبارية عبر البريد الإلكتروني",
                multilingual_support: "دعم متعدد اللغات",
                ongoing_maintenance: "صيانة مستمرة",
                custom_development: "تطوير مخصص"

            },
            chinees: {
                home: "首页",
                feature: "功能",
                maintenance: "维护",
                feedback: "反馈",
                build_websites: "我们构建强大的网站",
                unlock_power: "与全球超过100,000人一起解锁最强大的企业网站",
                easy_build: "轻松构建强大的网站",
                modern_websites: "我们的团队在几天内为您的网店和企业创建现代网站",
                unlock_access: "解锁访问",
                easy_build_most: "轻松构建最强大的网站",
                modern_websites_2: "我们的团队在几天内为您的网店和企业创建现代网站",
                unlock_access_2: "解锁访问",
                easy_build_strategies: "轻松构建强大的策略",
                modern_websites_3: "我们的团队在几天内为您的网店和企业创建现代网站",
                unlock_access_3: "解锁访问",
                basic: "基础版",
                basic_price: "$9.99/月",
                per_site: "每站每月",
                simple_design: "简单的设计和布局",
                home_page: "主页",
                contact_form: "联系表单",
                responsive_design: "响应式设计",
                basic_seo: "基本SEO设置",
                get_started: "开始使用",
                pro: "专业版",
                pro_price: "$17.99/月",
                all_basic: "包括基础版的所有功能",
                advanced_design: "高级设计",
                content_management: "内容管理系统",
                social_media: "社交媒体集成",
                enhanced_seo: "增强的SEO关键字搜索",
                premium: "高级版",
                premium_price: "$25.99/月",
                all_pro: "包括专业版的所有功能",
                ecommerce: "电子商务功能",
                advanced_analytics: "高级分析",
                blog_setup: "博客设置和集成",
                custom_graphics: "定制图形和品牌",
                website_maintenance: "网站维护",
                get_site_plan: "获取站点计划",
                ultra: "终极版",
                ultra_price: "$32.99/月",
                all_premium: "包括高级版的所有功能",
                additional_pages: "额外页面",
                content_creation: "内容创建",
                email_newsletter: "电子邮件通讯设置",
                multilingual_support: "多语言支持",
                ongoing_maintenance: "持续维护",
                custom_development: "定制开发"

            },
            spanish: {
                home: "Inicio",
                feature: "Característica",
                maintenance: "Mantenimiento",
                feedback: "Comentarios",
                build_websites: "Construimos sitios web poderosos",
                unlock_power: "Desbloquea los sitios web más poderosos para empresas con más de 100,000 personas a nivel mundial",
                easy_build: "Construcción fácil de sitios web poderosos",
                modern_websites: "Nuestro equipo crea sitios web modernos para tu tienda en línea, negocio en pocos días",
                unlock_access: "Desbloquear acceso",
                easy_build_most: "Construcción fácil de los sitios web más poderosos",
                modern_websites_2: "Nuestro equipo crea sitios web modernos para tu tienda en línea, negocio en pocos días",
                unlock_access_2: "Desbloquear acceso",
                easy_build_strategies: "Construcción fácil de estrategias poderosas",
                modern_websites_3: "Nuestro equipo crea sitios web modernos para tu tienda en línea, negocio en pocos días",
                unlock_access_3: "Desbloquear acceso",
                basic: "Básico",
                basic_price: "$9.99/mes",
                per_site: "Por sitio por mes",
                simple_design: "Diseño y maquetación simples",
                home_page: "Página de inicio",
                contact_form: "Formulario de contacto",
                responsive_design: "Diseño responsivo",
                basic_seo: "Configuración básica de SEO",
                get_started: "Comenzar",
                pro: "Pro",
                pro_price: "$17.99/mes",
                all_basic: "Todo de la versión básica",
                advanced_design: "Diseño avanzado",
                content_management: "Sistema de gestión de contenido",
                social_media: "Integración de redes sociales",
                enhanced_seo: "Búsqueda de palabras clave SEO mejorada",
                premium: "Premium",
                premium_price: "$25.99/mes",
                all_pro: "Todo de Pro",
                ecommerce: "Funcionalidad de comercio electrónico",
                advanced_analytics: "Analítica avanzada",
                blog_setup: "Configuración e integración de blogs",
                custom_graphics: "Gráficos personalizados y branding",
                website_maintenance: "Mantenimiento del sitio web",
                get_site_plan: "Obtener plan de sitio",
                ultra: "Ultra",
                ultra_price: "$32.99/mes",
                all_premium: "Todo de Premium",
                additional_pages: "Páginas adicionales",
                content_creation: "Creación de contenido",
                email_newsletter: "Configuración de boletines por correo electrónico",
                multilingual_support: "Soporte multilingüe",
                ongoing_maintenance: "Mantenimiento continuo",
                custom_development: "Desarrollo personalizado"

            },
            russia: {
                home: "Главная",
                feature: "Функции",
                maintenance: "Обслуживание",
                feedback: "Отзывы",
                build_websites: "Мы создаем мощные сайты",
                unlock_power: "Разблокируйте самые мощные сайты для бизнеса с более чем 100,000 человек по всему миру",
                easy_build: "Легко создавать мощные сайты",
                modern_websites: "Наша команда создает современные сайты для вашего интернет-магазина и бизнеса за несколько дней",
                unlock_access: "Разблокировать доступ",
                easy_build_most: "Легко создавать самые мощные сайты",
                modern_websites_2: "Наша команда создает современные сайты для вашего интернет-магазина и бизнеса за несколько дней",
                unlock_access_2: "Разблокировать доступ",
                easy_build_strategies: "Легко создавать мощные стратегии",
                modern_websites_3: "Наша команда создает современные сайты для вашего интернет-магазина и бизнеса за несколько дней",
                unlock_access_3: "Разблокировать доступ",
                basic: "Базовый",
                basic_price: "$9.99/месяц",
                per_site: "За сайт в месяц",
                simple_design: "Простой дизайн и макет",
                home_page: "Главная страница",
                contact_form: "Контактная форма",
                responsive_design: "Адаптивный дизайн",
                basic_seo: "Основная настройка SEO",
                get_started: "Начать",
                pro: "Про",
                pro_price: "$17.99/месяц",
                all_basic: "Все из базовой версии",
                advanced_design: "Продвинутый дизайн",
                content_management: "Система управления контентом",
                social_media: "Интеграция социальных сетей",
                enhanced_seo: "Улучшенный поиск ключевых слов SEO",
                premium: "Премиум",
                premium_price: "$25.99/месяц",
                all_pro: "Все из версии Про",
                ecommerce: "Функциональность электронной коммерции",
                advanced_analytics: "Продвинутый анализ",
                blog_setup: "Настройка и интеграция блога",
                custom_graphics: "Индивидуальная графика и брендинг",
                website_maintenance: "Обслуживание сайта",
                get_site_plan: "Получить план сайта",
                ultra: "Ультра",
                ultra_price: "$32.99/месяц",
                all_premium: "Все из версии Премиум",
                additional_pages: "Дополнительные страницы",
                content_creation: "Создание контента",
                email_newsletter: "Настройка электронных новостных рассылок",
                multilingual_support: "Поддержка нескольких языков",
                ongoing_maintenance: "Постоянное обслуживание",
                custom_development: "Индивидуальная разработка"

            }
        };


        function translatePage(language) {
            const elements = document.querySelectorAll('[data-translate-key]');
            elements.forEach(element => {
                const key = element.getAttribute('data-translate-key');
                if (translations[language][key]) {
                    element.innerText = translations[language][key];
                }
            });
        }